In [3]:
# Comprehensions

keyfile='DataFiles/key.txt'

def dictionarykeyfile(keyfile):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key

keyfile='DataFiles/key.txt'
key=dictionarykeyfile(keyfile)

evenkeys={item for item in key.items() if int(item[0])%2==0}
evenkeys

{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

# Numpy Library

- processing  N-Dimensional arrays


In [8]:
import numpy as np

li=[1,2,3]
a=np.array(li)
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
rn=np.random.randint(0,100,size=10)
rn

array([74, 10, 20, 79, 70, 32, 20, 65, 63, 27])

In [15]:
rn=np.random.randint(0,100,size=(3,3))
rn

array([[72, 96, 39],
       [89, 44, 19],
       [93, 69, 93]])

In [16]:
rn[1][2]

19

In [17]:
rn.size

9

In [18]:
rn.ndim

2

In [19]:
b.ndim

1

In [21]:
rn.shape

(3, 3)

# Pandas

**uses cases**

- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- Series
- Data Frames

In [24]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':10}

internal1=pd.Series(internal1)
internal1

internal2={'s1':11,'s2':8,'s3':4}
internal2=pd.Series(internal2)
internal2

s1    11
s2     8
s3     4
dtype: int64

In [33]:
final={'Internal 1':internal1,'Internal 2':internal2}
final=pd.DataFrame(final)
final

Internal 1  Internal 2
s1          21          11
s2          18           8
s3          10           4

In [35]:
final.columns  #Name of all columns

final.values# final.values #List of all rows

array([[21, 11],
       [18,  8],
       [10,  4]], dtype=int64)

In [38]:
final.values[2]

array([10,  4], dtype=int64)

In [40]:
for row in final.values:
    print('Internal 1 - ',row[0],',','Interanl 2 -',row[1])

Internal 1 -  21 , Interanl 2 - 11
Internal 1 -  18 , Interanl 2 - 8
Internal 1 -  10 , Interanl 2 - 4


In [41]:
final.loc['s4']=[19,23]
final

Internal 1  Internal 2
s1          21          11
s2          18           8
s3          10           4
s4          19          23

In [46]:
final=final.drop('s3')

In [47]:
final

Internal 1  Internal 2
s1          21          11
s2          18           8

In [50]:
#Reading CSV File data

import pandas as pd
incomedf=pd.read_csv("DataFiles/income.csv")
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [53]:
#Extract income of all states in 2013

#Calofornia

for row in incomedf.values:
    print(row[1],":",row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [57]:
#Avg income of Arizona

sum=0
count=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
    count+=1
    
sum/count

47214.77777777778

In [62]:
# Avg income of all states for year 2012
sum=0
count=0
for i in incomedf.values:
    sum+=i[-2]
    count+=1
sum//count

50038

In [ ]:
t=int(input())

def freq(l):
    h=[]
    for i in range(0,len(l)-1):
        for j in range(1,len(l)):
            d=abs(l[i]-l[j])
        l.append(d)
    print(min(l))
            


for i in range(t):
    l=list(map(int,input().split()))
    freq(l)

3
3 6 9 15
3
25 50 100 108
25
